### ISSUE TITLE
Citing CBC in the scientific literature

### ISSUE THREAD

**Issue by bertrand-caron** [coin-or/Cbc.old#20]
Hi,

I am currently writing a scientific paper describing work I have done which relied on CBC as my ILP solver.
I was wondering what was the best way to credit CBC.
I've unsuccessfully looked for citing instructions on the FAQ and README.

If no "reference" paper has been published, have you considered using [Zenodo](https://zenodo.org)? It's a free service allowing you to get a DOI for each release, that can then be cited; and is very easy to set up.

Thanks a lot for your time,
Bertrand

**Comment by jiadongwang** [comment]
there are already some projects on Zenodo, such as 
https://zenodo.org/record/246087#.W0VywNVKipo
It seems Cbc is not on Zenodo. 
Or you can cite the binary? many people just use https://projects.coin-or.org/Cbc
https://bintray.com/coin-or/download/Cbc

**Comment by bertrand-caron** [comment]
Hi Jiadong, thanks for your answer.

Using Zenodo would allow referencing particular commits (releases) of CBC with a unique DOI.
You also get a badge with a DOI that you can add to the `README.md` of the project.
If it's not too much to set up, that might be the best option, otherwise I can always cite the binary.

Best, Bertrand

**Comment by tkralphs** [comment]
I've been assigning DOIs using Zenodo for releases to many of the COIN-OR projects, but Cbc has unfortunately not had a release since I started doing it. I really want to make a release soon, but it is a time-consuming process. If necessary, I can go back and put the latest existing release on Zenodo.  How soon are you planning to submit the paper?

**Comment by bertrand-caron** [comment]
Hi Ted, a release for the latest existing version on Zenodo would be great! I'd like to submit the paper around the first week of August, would that be an acceptable timeframe for you?

**Comment by tkralphs** [comment]
I created a DOI for 2.9.9 on Zenodo and added the link to the README. Hope this helps!

**Comment by bertrand-caron** [comment]
Thanks a lot, I hope you get many citations (which you all deserve)!
